version: '3'

services:
  etl:
    build:
      context: .
    container_name: etl
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
